# Generated by Django 5.0.6 on 2024-05-29 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_payment_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default='True', verbose_name='активность'),
        ),
    ]
