# Generated by Django 5.0.6 on 2024-06-10 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_payment_stripe_checkout_url_payment_stripe_price_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='stripe_checkout_url',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='URL страницы оплаты в Stripe'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='stripe_price_id',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='ID цены в Stripe'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='stripe_product_id',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='ID продукта в Stripe'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='stripe_session_id',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='ID сессии в Stripe'),
        ),
    ]
