# Generated by Django 5.0.6 on 2024-06-03 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_alter_course_options_alter_lesson_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription',
            name='created_at',
        ),
    ]
