# Generated by Django 5.0.6 on 2024-06-10 04:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_stripepayment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StripePayment',
        ),
    ]
